jmerle/competitive-companion

src/parsers/problem/CodeforcesProblemParser.ts

So, when you parse Codeforces problem in Russian interfaces, input/output is set to files called "стандартный ввод/стандартный вывод" (that is standard input/standard output in Russian).
Note, I made a patch how I think it could look like, **but I didn't test it** because I am not sure how to create environment for that. It may not work, for example, because of encoding issues.

CodeForces parser doesn't work with Russian interface

---

src/parsers/problem/FacebookHackerCupProblemParser.ts
tests/data/facebook-hacker-cup/problem/normal.json

It seems the "pattern" attribute has been mistakenly left from and old version that supported regex. With no "fileName" attribute, CHelper fails to parse problems.

Fix FacebookHackerCup parser

---

src/parsers/problem/AtCoderProblemParser.ts
tests/data/atcoder/problem/normal_ja.json

Most of problems in AtCoder are written in English and Japanese, but some problems are written in Japanese only.
ex) https://atcoder.jp/contests/colopl2018-final/tasks/colopl2018_final_a
So I replaced `Sample Input` / `Sample Output` to `入力例` / `出力例` to be able to parse test cases for all problems.

Support AtCoder problems written in Japanese

---

src/parsers/problem/SPOJProblemParser.ts
tests/data/spoj/problem/multiple-blocks.json

SPOJ parser didn't parse tests when there are separate areas for each input and output and they start with "Example Input".

Add support for multiple test blocks in SPOJ parser

---

src/parsers/problem/CodeforcesProblemParser.ts
tests/data/codeforces/problem/gym.json

In one of last commits was added "a[href*="/contest"]" to the path of querySelector. It works well in contests, but absolutely fails in gyms. To fix that we have to change "/contest" to "/gym" when we are in gym.
This bug was mentioned in #83

Fix parsing Codeforces gym problems

---

src/parsers/problem/TophProblemParser.ts
tests/data/toph/problem/time-limit-in-ms.json

Toph parser didn't expect that time limit can be given in milliseconds.

Fix parsing time limits in ms in Toph parser

---

src/parsers/problem/GoogleCodingCompetitionsProblemParser.ts
tests/data/google-coding-competitions/problem/codejam.json
tests/data/google-coding-competitions/problem/kickstart.json
tests/data/google-coding-competitions/problem/multiple-samples.json
tests/parser-functions.ts

The current parser parses the first block of io only, but some problems have more than one block.

Add support for multiple test blocks in Google competitions

---

src/parsers/problem/CodeforcesProblemParser.ts
tests/data/codeforces/problem/acm-sgu-ru-inside-table.json

For example, this problem was unparseable: https://codeforces.com/problemsets/acmsguru/problem/99999/123?locale=en

Fix parsing memory limit in some acmsguru problems in the Codeforces parser

---

src/parsers/problem/YandexProblemParser.ts

Some contests look like 'https://official.contest.yandex.ru/contest/18275/problems/E/'. They have 'yandex.ru/contest', but not 'yandex.ru/*/contest'.
I decided to change patterns building so that I won't add 4 more lines just to add this change.

Add support for one more yandex contest link type

---

src/parsers/problem/DMOJProblemParser.ts

Steps to replicate original bug:
1. Log into your DMOJ account
2. Pick a problem you've already submitted to
3. Use Competitive Companion to fetch that problem
The fetched info will have an empty problem name.  Not really sure how to add this to unit tests since you have to be logged in, maybe something involving DMOJ API tokens could work.
To fix the issue, I just slightly changed the selector used for finding the problem name.

Bugfix: DMOJ parser gives empty name when parsing problems that have already been attempted (submitted to).

---

src/parsers/problem/CSESProblemParser.ts
tests/data/cses/problem/code_blocks_in_statement.json

The parser previously matched any code as sample input/output, including
when there were code blocks as part of the output specification or
problem statement (example: https://cses.fi/problemset/task/1729).
Fixed this by only matching the first two code blocks after each
"example" header (and added a test).

Fix CSES parser to exclude code blocks in statement

---

src/parsers/parsers.ts
src/parsers/problem/OldLibraryCheckerProblemParser.ts

Since `old.yosupo.jp` is still alive and I prefer solving problem on it, so I'd like add back the previous version parser for it with a new name `OldLibraryCheckProblemParser`.
Thanks for your review whatever!

add back previous version library checker parser for old.yosupo.jp

---

src/parsers/problem/KattisProblemParser.ts

This is a possible pattern for Kattis URL too.
Example URL format: https://abc.kattis.com/sessions/ab12cd/problems/problemname (not real URL)

Support custom session in Kattis

---

src/parsers/contest/HDOJNGContestParser.ts
src/parsers/parsers.ts
src/parsers/problem/HDOJNGProblemParser.ts

HDUOJ has updated new UI in the recent contests, the original parser is not available with the new UI. It can be distinguished simply by the URL prefix.
The new UI currently is only used in the recent contests, problem archive is still using the old UI.

Add HDOJ NG Parser

---

src/parsers/problem/BaekjoonOnlineJudgeProblemParser.ts

[BOJ Stack](https://stack.acmicpc.net/) is a site used to upload problems to [BOJ](https://www.acmicpc.net/).
It provides a preview feature when editing problems, and this preview page can be parsed with BaekjoonOnlineJudgeProblemParser. 
So, I think it would be helpful to add the BOJ stack to this parser.

Add BOJ Stack parsing in BaekjoonOnlineJudgeProblemParser

---

src/parsers/problem/TLXProblemParser.ts

I noticed that the parser does not work with problems accessed through the available courses ([example](https://tlx.toki.id/courses/competitive/chapters/06/problems/C)), so I added the URL patterns and updated the title parser which seems to be the only difference with regular problems. I also fixed an error when the problem uses millisecond as the unit of the time limit, which would not work with the current regex pattern ([example](https://tlx.toki.id/problems/tsoc-april-fools-2021/A)). The output parser also now returns an empty string `""` if the element containing the output example cannot be found ([example](https://tlx.toki.id/courses/basic/chapters/05/problems/B)).

Fix TLX Parser

---

src/parsers/parsers.ts
src/parsers/problem/BAPSOJProblemParser.ts

Add support for BAPS OJ

---

README.md
package.json
pnpm-lock.yaml
src/parsers/contest/DOMjudgeContestParser.ts
src/parsers/parsers.ts

This PR introduces contest parsing for [DOMjudge](https://www.domjudge.org/), the large prominent contest control system for all ICPC contests.
<p align="center">
<a href=https://www.domjudge.org/demoweb/public/problems> demoweb </a>
</p>
Frankly, I was surprised that no one had mentioned it yet. Maybe because it is not a classic online judge, but a self-hosted software. Many universities use it for assignments and contests.
I wish the match pattern was better, but due to a lot of different hosts, a URL cannot be defined. I hope the `canHandlePage()` helps.
The parser itself looks at a lot of different elements, because I wanted to support the layout of DOMjudge 7 and DOMjudge 8.
Unfortunately, the sample testcases for contests and problems are not directly available. Only behind a …

Added DOMjudge Contest Parser (+ JSZip)

---

README.md
src/parsers/parsers.ts
src/parsers/problem/MendoProblemParser.ts

[Mendo](https://mendo.mk) _(Macedonian: МЕНДО, pronounced phonetically)_ is a competitive programming website designed to teach and archive problems from Macedonian contests and others such as EJOI and JBOI. It serves as a standalone judge for its problems and accepts Pascal, C, C++ and Java as submission languages. Its servers are on the Macedonian faculty of FINKI _(ФИНКИ, abbrevation)_, in Skopje.
Added **problem parser** for problems on Mendo. It should work with all of them, even if the HTML doesn't have a specific schema. It also somewhat distinguishes interactive problems.
Base URL for a problem is https://mendo.mk/Task.do, and it uses this regex to recognize a problem URL:
```js
/^https?:\/\/(?:www\.)?mendo\.mk\/Task\.do\?id=\d+$/
```
The catch is that some problems are only in …

Mendo problem parser

---

README.md
package.json
pnpm-lock.yaml
src/background.ts

I noticed Competitive Companion is getting slower with time, and it's mainly due to the fact that:
1. The number of custom hosts (ports to send the parsed problems to) has increased significantly;
2. We issue requests to those hosts serially (N requests, but usually only 1 really matters), regardless of whether they were good or not.
By making these requests in parallel, we can get a ~8x speed-up in contest parsing.
Serial calls:
Parallel calls:
Will be happy to do any other changes deemed necessary to get this through, the speed up was really helpful for me.
EDIT:
It's worth mentioning that I'm using WSL, and I'm not sure the extension is particularly slow because of that. Since it seems the code is like this for a long time, maybe the impact isn't noticeable in most of the cases (well, …

Call custom hosts in parallel

---

src/utils/request.ts

Custom User-Agent at `utils/request`

---

src/parsers/problem/KattisProblemParser.ts

I just add one more matching path for Kattis problems, so that the URL matches links such as 
https://tamu.kattis.com/courses/CSCE430/2025Spring/assignments/jzms2e/problems/carrots.

Allow problems from courses

---

README.md
src/parsers/problem/DMOJProblemParser.ts

Currently, attempting to use the extension on AYOJ (https://ayjcoding.club/) gives an error. This can be easily fixed by using the already implemented DMOJ problem and contest parsers, which works as expected.

Add AYOJ support using the existing DMOJ problem & contest parser
