- src/parsers/contest/AtCoderContestParser.ts
- src/parsers/problem/AtCoderProblemParser.ts
AtCoder has officially released its new version of webpage, and now its URI scheme has changed.
I rewrote URL match patterns to support this new scheme.
> Support new atcoder URI scheme

- src/parsers/problem/NewGoogleCodeJamProblemParser.ts
- tests/data/new-google-code-jam/problem/normal.json
Fixed issue on the CodeJam parser where the problem and contest names were swapped.
Fixes: #32
> Fixes CodeJam parsing issue

- README.md
- src/hosts/hosts.ts
acmX is tool I've been developing for VSCode.
+ https://marketplace.visualstudio.com/items?itemName=marx24.acmx
+ https://github.com/mfornet/acmx
> Add acmX to known hosts

- src/parsers/problem/AtCoderProblemParser.ts
Because in AtCoder contests held before AtCoder Beginner Contests 016, latest version of competitive-companion is not able to parse input and output correctly.
I changed if statement in AtCoderProblemParser.ts.
> Fix AtCoder parser for some old contests.

- src/parsers/parsers.ts
- src/parsers/problem/NowCoderProblemParser.ts
Add [Nowcoder](https://ac.nowcoder.com/acm/home/699496297) parser
> Add NowCoder parser

- src/parsers/ContestParser.ts
- src/parsers/contest/CodeforcesContestParser.ts
- tests/data/codeforces/contest/statements-in-pdf.json
If codeforces parser failed it is probably because there are no page problem available.
This is the case from this contest for example: https://codeforces.com/gym/100524
Try to parse anyway the contest with available information.
> Parse Codeforces contest without page problem

- src/parsers/contest/HackerRankContestParser.ts
Group the challenges by the contest value found in breadcrumb.
> Hackerrank groupby contest

- src/parsers/parsers.ts
- src/parsers/problem/TLXProblemParser.ts
- tests/data/tlx/problem/from_contest_en.json
- tests/data/tlx/problem/from_contest_id.json
- tests/data/tlx/problem/from_problemset_en.json
- tests/data/tlx/problem/from_problemset_id.json
- tests/parser-functions.ts
Supports English and Indonesian.
Supports contests & upsolving from the problemset.
I based the code on the existing AtCoder parser.
> Add parser for TLX (tlx.toki.id)

- README.md
- src/hosts/hosts.ts
> Support for Competitive Programming Gradle Plugin

- README.md
> Add cphelper.nvim to supported tools

- src/parsers/parsers.ts
- src/parsers/problem/XXMProblemParser.ts
- tests/data/xxm/problem/normal.json
the XXM oj is local website used by hundreds students who learning competitive programming.
Hope that this contribution can be considered in next release. Thanks so much.
> add XXM problem parser

- src/parsers/problem/LibraryCheckerProblemParser.ts
- tests/before-functions.ts
Library Checker seems to have changed its CSS.
> Fix LibraryChecker Parser

- src/parsers/parsers.ts
- src/parsers/problem/PTAProblemParser.ts
- src/parsers/problem/ZOJProblemParser.ts
- tests/before-functions.ts
- tests/data/pta/problem/normal.json
- tests/data/zoj/problem/normal.json
PTA example problem: https://pintia.cn/problem-sets/994805342720868352/problems/994805528788582400
ZOJ example problem: https://zoj.pintia.cn/problem-sets/91827364500/problems/91827364500
They are both single-page applications, which are more difficult to fetch the contest.
> Add PTA & ZOJ Parser

- src/parsers/parsers.ts
- src/parsers/problem/LSYOIProblemParser.ts
This parser is the parser for LSYOI, and this one is run correctly in my local environment.
> Add LSYOI Parser

- src/parsers/parsers.ts
- src/parsers/problem/OTOGProblemParser.ts
- tests/data/otog/problem/normal.json
Problem parser for OTOG, one of the online grader in Thailand
Example https://otog.cf/problem/1
> Add OTOG problem parser

- src/parsers/problem/CodeforcesProblemParser.ts
Some problems, such as [CF576E](https://codeforces.com/problemset/problem/576/E), have a memory or time limit in bold. That is, they have the class "tex-font-style-bf".
> Add bold text support.

- README.md
- src/parsers/parsers.ts
- src/parsers/problem/TheJobOverflowProblemParser.ts
resolves #356 
I tested and it works.
> Add TheJobOverflow Problem Parser

- README.md
- src/parsers/parsers.ts
- src/parsers/problem/DimikOJProblemParser.ts
resolves #357 
Ok, I figured things out and added the problem parser myself.
Tested for multiple problems and working.
**UPDATE:** I have tested this pr for all 52 problems in DimikOJ and it works fine.
> Add DimikOJ Problem Parser

- src/parsers/problem/CodeforcesProblemParser.ts
The extension cannot detect some problems like this one:
https://codeforces.com/problemset/gymProblem/101744/A
This Pull Request adds this pattern to the parser.
> Add a pattern in CodeforcesProblemParser

- src/parsers/contest/HDOJContestParser.ts
- src/parsers/contest/HDOJNewContestParser.ts
- src/parsers/contest/UOJContestParser.ts
- src/parsers/problem/HDOJNewProblemParser.ts
- src/parsers/problem/HDOJProblemParser.ts
- src/parsers/problem/UOJProblemParser.ts
> Add DaimayuanOJ Parser

- README.md
- src/parsers/parsers.ts
- src/parsers/problem/ITCoderHUTECHProblemParser.ts
> Add support for ITCoder HUTECH

- src/parsers/problem/AlgoZenithNewProblemParser.ts
Problem Parser for New AlgoZenith site (maang.in) was not working. Fixed that.
> Fixed the AlgoZenithNewProblemParser

- src/parsers/contest/VirtualJudgeContestParser.ts
- src/parsers/problem/VirtualJudgeProblemParser.ts
> Add patterns for `vjudge.net.cn`

- src/parsers/problem/PTAProblemParser.ts
fixes #437
It looks like query string was the issue. Adding a wildcard at the end to match query string solves it.
> Fix problems with PTA OJ

- src/parsers/problem/TLXProblemParser.ts
fixes #436 
**Note:** I tried to fix the issue by doing minimal changes to the code. It works. But, it feels like the code needs to be rewritten as the UI has probably has undergone major rework. I am not sure if some parts of the old code like:
https://github.com/jmerle/competitive-companion/blob/877716ec913dfe6c740df3c39229b8c51a52bf6e/src/parsers/problem/TLXProblemParser.ts#L65-L82
is still viable or not. But since I needed to change the class names of all other parts, probably not.
> fix problems with TLXProblemParser

- README.md
- src/parsers/contest/LanqiaoContestParser.ts
- src/parsers/parsers.ts
- src/parsers/problem/LanqiaoProblemParser.ts
> Add LanqiaoProblemParser

- README.md
Note: Also needs to be changed from GitHub metadata. Resolves: #448 .
> update chrome web store link in readme

- src/parsers/problem/ACMPProblemParser.ts
> fixes #470

- src/parsers/problem/EolympBasecampProblemParser.ts
> fix EolympBasecampProblemParser

- README.md
- src/parsers/contest/LightOJContestParser.ts
- src/parsers/parsers.ts
- src/parsers/problem/LightOJProblemParser.ts
resolves #500 
Issues needing review:
1. Limits div cannot be parsed in contest arena problems for some reason.
2. I made a contest with 3 problems for testing but only 2 were parsed. No clue why.
They are not letting me open a public contest for free, so if you want to test, let me know with a comment with your LightOJ username for author access or open a private contest yourself.
Contest Link: https://lightoj.com/contest/competitive-companion-test
Author's Dashboard Link: https://lightoj.com/author/contest/3666/
> Add LightOJ contest parser

- README.md
- src/parsers/parsers.ts
- src/parsers/problem/QBXTOJProblemParser.ts
> Add support for QBXTOJ

- src/parsers/problem/HydroProblemParser.ts
[CYEZOJ](https://newoj.cyezoi.com) is a type of Hydro OJ
> Support CYEZOJ

- README.md
- src/parsers/parsers.ts
- src/parsers/problem/MarisaOJProblemParser.ts
Example problem: https://marisaoj.com/problem/284
> Add MarisaOJ problem parser

- README.md
- src/parsers/parsers.ts
- src/parsers/problem/XCampProblemParser.ts
Example problem: https://contest.x-camp.org/contest/367/problem/1767
> Add X-Camp Problem Parser

- scripts/build/extension.ts
- src/background.ts
- src/hosts/CustomHost.ts
- src/hosts/Host.ts
- src/hosts/hosts.ts
- src/options.html
- src/options.ts
- src/utils/config.ts
firstly, solving #541 issue using `no-cors` option.
As i writing extension's setting options,
I found that custom fields input check is wrong, so i solved that minor issues too.
And make fillCustomValues() function due to check my custom field's input value.
I cant check my input when re-opening options page, so i make this function and load my current setting values.
> feat: config custom hostname

- scripts/build/extension.ts
- src/background.ts
- src/hosts/CustomHost.ts
- src/hosts/Host.ts
- src/hosts/hosts.ts
- src/options.html
- src/options.ts
- src/utils/config.ts
See https://github.com/jmerle/competitive-companion/issues/549#issuecomment-2654468548
> Revert "feat: config custom hostname"

- README.md
- Add `assistant.nvim` to tool list in the readme
> [DOCS] Update README for new tool

- src/parsers/problem/PTAProblemParser.ts
> Fix PTA match_pattern

- README.md
- src/parsers/parsers.ts
- src/parsers/problem/OlympicodeProblemParser.ts
https://olympicode.rs
Example problem: https://olympicode.rs/problem/11
> Add Olympicode Problem Parser

- src/parsers/parsers.ts
- src/parsers/problem/HOJProblemParser.ts
Add support for HOJ.
Due to the expiration of HOJdemo, an example of LZUOJ is provided.
https://lzuoj.lzu.edu.cn/home
https://lzuoj.lzu.edu.cn/problem/A1000
> Add support for HOJ
